language: android
script:
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - export TERM=dumb
  - echo sdk.dir $ANDROID_HOME > local.properties
  - jdk_switcher use oraclejdk8
  - ./gradlew test
android:
  components:
  - tools
  - build-tools-29.0.2
  - android-29
before_install:
 - yes | sdkmanager "platforms;android-29"
