# SPDX-FileCopyrightText: 2015, microG Project Team
# SPDX-License-Identifier: CC0-1.0

jobs:
  include:
    - name: "Build and Test"
      language: android
      android:
        components:
          - tools
          - build-tools-29.0.3
          - android-29
      script:
        - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
        - export TERM=dumb
        - echo sdk.dir $ANDROID_HOME > local.properties
        - jdk_switcher use oraclejdk8
        - ./gradlew build
        - ./gradlew test
    - name: "REUSE lint"
      language: minimal
      script:
        - docker pull fsfe/reuse:latest
        - docker run -v ${TRAVIS_BUILD_DIR}:/data fsfe/reuse:latest lint
